## driver name
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## mysql url
#spring.datasource.url=jdbc:mysql://localhost:3306/covid
## mysql username
#spring.datasource.username=root
## mysql password
#spring.datasource.password=25gn3umb
## the log of mybatis
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
##a_column ------> aCloumn
#mybatis.configuration.map-underscore-to-camel-case=true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/covid
    username: root
    password: 25gn3umb

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


server:
  port: 8080
